name: Deploy Backend to o2switch

on:
  push:
    branches: [ main ] # Se d√©clenche lors d'un push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run remote command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /var/www/acsv2/backend
            git pull
            rm -rf dist
            pm2 restart acs-backend-v2