name: Deploy Backend to o2switch

on:
  push:
    branches: [ main ] # Se déclenche lors d'un push sur main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          npm run build:ts  # Génère le dossier dist/

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }} # ou key
          port: 22
          source: ./dist
          target: /acs-backend-v2
          exclude: |
            node_modules/**
            src/**
            .git/**
            .github/**
            tsconfig.json
            externaldata/**